name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Download and extract Android SDK
        run: |
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O android-sdk-tools.zip
          mkdir -p $HOME/android-sdk
          unzip -q android-sdk-tools.zip -d $HOME/android-sdk

      - name: Accept licenses
        run: yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses

      - name: Set up environment variables
        run: |
          echo 'export ANDROID_HOME=$HOME/android-sdk' >> $GITHUB_ENV
          echo 'export PATH=$PATH:$HOME/android-sdk/cmdline-tools/tools/bin:$HOME/android-sdk/platform-tools' >> $GITHUB_ENV

      - name: Install Buildozer
        run: pip install buildozer

      - name: Configure Buildozer
        run: buildozer init

      - name: Build APK
        run: buildozer -v android debug

      # Upload the APK as an artifact
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: my_app
          path: ./bin/*.apk
